apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgreschart.fullname" . }}-postgres
  labels:
    app: postgres
  {{- include "postgreschart.labels" . | nindent 4 }}
  annotations:
    notifications.argoproj.io/subscriptions: |
      - trigger: [on-created, on-deployed, on-deleted, on-sync-succeeded, on-scaling-replica-set, on-rollout-updated, on-rollout-step-completed]
        destinations:
          - service: slack
            recipients: [my_channel]
      - trigger: [on-rollout-aborted, on-analysis-run-failed, on-analysis-run-error]
        destinations:
          - service: slack
            recipients: [my_channel]
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres
  serviceName: {{ include "postgreschart.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "postgreschart.fullname" . }}-config
        image: {{ .Values.postgres.postgres.image.repository }}:{{ .Values.postgres.postgres.image.tag
          | default .Chart.AppVersion }}
        name: postgres
        ports:
        - containerPort: 5432
        resources: {{- toYaml .Values.postgres.postgres.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "postgreschart.fullname" . }}-pvc
  updateStrategy: {}