apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgreschart.fullname" . }}-config
  labels:
    app: postgres
  {{- include "postgreschart.labels" . | nindent 4 }}
data:
  PGDATA: {{ .Values.config.pgdata | quote }}
  POSTGRES_DB: {{ .Values.config.postgresDb | quote }}
  POSTGRES_PASSWORD: {{ .Values.config.postgresPassword | quote }}
  POSTGRES_USER: {{ .Values.config.postgresUser | quote }}