apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  labels:
    app: flask
  {{- include "flaskchart.labels" . | nindent 4 }}
spec:
  selector:
    app: flask-monitor
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}
  type: "LoadBalancer"