config:
  dbEngine: postgresql
  dbHost: postgres
  dbPort: "5432"
  debug: "False"
  secretKey: S3cr3t_K#Key
monitor:
  flask:
    image:
      repository: sushanku/flask-monitor-app
      tag: latest
    port:
      containerPort: 5000
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  replicas: 1
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
