apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskchart.fullname" . }}-monitor
  labels:
    app: flask-monitor
  {{- include "flaskchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitor.replicas }}
  selector:
    matchLabels:
      app: flask-monitor
    {{- include "flaskchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: flask-monitor
      {{- include "flaskchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "flaskchart.fullname" . }}-config
        image: {{ .Values.monitor.flask.image.repository }}:{{ .Values.monitor.flask.image.tag
          | default .Chart.AppVersion }}
        name: flask
        ports:
        - containerPort: 5000
        resources: {{- toYaml .Values.monitor.flask.resources | nindent 10 }}