apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "flaskchart.fullname" . }}-monitor-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: {{ include "flaskchart.fullname" . }}-monitor-secret
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /DB_HOST
    - secretKey: DB_PASS
      remoteRef:
        key: /DB_PASSWORD
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /DB_PASSWORD
    - secretKey: DB_USERNAME
      remoteRef:
        key: /DB_USERNAME
    - secretKey: DB_NAME
      remoteRef:
        key: /DB_NAME
