apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskchart.fullname" . }}-monitor
  labels:
    app: flask-monitor
    {{- include "flaskchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitor.replicas }}
  selector:
    matchLabels:
      app: flask-monitor
      {{- include "flaskchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: flask-monitor
        {{- include "flaskchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: flask
        image: {{ .Values.monitor.flask.image.repository }}:{{ .Values.monitor.flask.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.monitor.flask.port.containerPort }}
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
          # - secretRef:
          #     name: {{ include "flaskchart.fullname" . }}-monitor-secret
          - configMapRef:
              name: {{ include "flaskchart.fullname" . }}-config
        resources: {{- toYaml .Values.monitor.flask.resources | nindent 10 }}
        # livenessProbe:
        #   httpGet:
        #     path: "/login"
        #     port: {{ .Values.monitor.flask.port.containerPort }}
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: "/login"
        #     port: {{ .Values.monitor.flask.port.containerPort }}
        #   initialDelaySeconds: 15
        #   periodSeconds: 8
        #   timeoutSeconds: 5
        #   failureThreshold: 5
