apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgreschart.fullname" . }}-pvc
  labels:
  {{- include "postgreschart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.postgresPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresPvClaim.storageClass | quote }}