apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitorapp-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sushan/kubedata"


# for EKS cluster this physical volume is not needed. EKS provisions the physical volume.