apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "monitor_db"
  POSTGRES_USER: "sushanku"
  POSTGRES_PASSWORD: "monitor01"