{{- define "application" -}}
{{- $root := . }}
{{- range $application := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}-{{ $root.Values.environment }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default "default" $application.project }}
  destination:
    server: {{ $root.Values.spec.destination.server }}
    namespace: monitoring
  source:
    repoURL: {{ $root.Values.spec.source.repoURL }}
    targetRevision: {{ $root.Values.spec.source.targetRevision }}
    path: "eks_helm/{{ $application.name }}"
    {{- if $application.valueFiles }}
    helm:
      valueFiles:
      {{- range $vf := $application.valueFiles }}
        - {{ $vf }}
      {{- end }}
    {{- else }}
    helm: {}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}