{{- define "application" -}}
{{- $root := . }}
{{- range $application := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}-{{ $root.Values.environment }}
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscriptions: |
      - trigger: [on-created, on-deployed, on-deleted, on-sync-succeeded, on-scaling-replica-set, on-rollout-updated, on-rollout-step-completed]
        destinations:
          - service: slack
            recipients: [ "{{ $application.notify_channel }}" ]
      - trigger: [on-rollout-aborted, on-analysis-run-failed, on-analysis-run-error]
        destinations:
          - service: slack
            recipients: [ "{{ $root.Values.notify_channel }}" ]
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default "default" $application.project }}
  destination:
    server: {{ $root.Values.spec.destination.server }}
    namespace: default
  source:
    repoURL: {{ $root.Values.spec.source.repoURL }}
    targetRevision: {{ $root.Values.spec.source.targetRevision }}
    path: "eks_helm/{{ $application.name }}"
    {{- if $application.valueFiles }}
    helm:
      valueFiles:
      {{- range $vf := $application.valueFiles }}
        - {{ $vf }}
      {{- end }}
    {{- else }}
    helm: {}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
{{- end }}